// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "description": "이메일과 비밀번호로 로그인",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "로그인",
                "parameters": [
                    {
                        "description": "로그인 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.TokenResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "description": "로그아웃 (클라이언트에서 토큰 삭제)",
                "tags": [
                    "Auth"
                ],
                "summary": "로그아웃",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.Response"
                        }
                    }
                }
            }
        },
        "/api/auth/refresh": {
            "post": {
                "description": "Refresh Token으로 Access Token 갱신",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "토큰 갱신",
                "parameters": [
                    {
                        "description": "Refresh Token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.TokenResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "description": "이메일과 비밀번호로 회원가입",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "회원가입",
                "parameters": [
                    {
                        "description": "회원가입 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.TokenResponse"
                        }
                    }
                }
            }
        },
        "/api/chat/session": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "새로운 대화 세션 생성 (오늘의 5문장 세트와 연결)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "대화 세션 생성",
                "parameters": [
                    {
                        "description": "세션 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chat.CreateSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.ChatSession"
                        }
                    }
                }
            }
        },
        "/api/chat/session/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "대화 세션 상세 정보 조회 (메시지 포함)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "대화 세션 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "세션 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ChatSession"
                        }
                    }
                }
            }
        },
        "/api/chat/session/{id}/end": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "대화 세션을 종료하고 통계 저장",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "대화 세션 종료",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "세션 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "종료 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chat.EndSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ChatSession"
                        }
                    }
                }
            }
        },
        "/api/chat/sessions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "유저의 최근 대화 세션 목록 조회",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "대화 세션 목록 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "페이지 번호",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "페이지당 개수",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.PaginatedResponse"
                        }
                    }
                }
            }
        },
        "/api/feedback/{sessionId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "세션 ID로 피드백 조회 (총점, 문법, 발음, 자연스러움 등)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feedback"
                ],
                "summary": "대화 피드백 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "세션 ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Feedback"
                        }
                    }
                }
            }
        },
        "/api/learning/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "전체 학습 진행 히스토리 조회",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Learning"
                ],
                "summary": "학습 히스토리 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "페이지 번호",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "페이지당 개수",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.PaginatedResponse"
                        }
                    }
                }
            }
        },
        "/api/learning/progress": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "문장별 이해/말하기/확인/암기 완료 상태 업데이트",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Learning"
                ],
                "summary": "학습 진행 상황 업데이트",
                "parameters": [
                    {
                        "description": "진행 상황",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/learning.UpdateProgressRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.LearningProgress"
                        }
                    }
                }
            }
        },
        "/api/learning/today": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "오늘의 5문장 학습 진행 상황 조회",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Learning"
                ],
                "summary": "오늘의 학습 진행 상황 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Daily Set ID",
                        "name": "daily_set_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.TodayProgressResponse"
                        }
                    }
                }
            }
        },
        "/api/sentences/daily": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "유저의 레벨/관심사 기반 오늘의 5문장 반환 (첫 호출 시 생성)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sentences"
                ],
                "summary": "오늘의 5문장 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sentences.DailySentencesResponse"
                        }
                    }
                }
            }
        },
        "/api/sentences/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "유저가 학습한 문장 히스토리 조회",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sentences"
                ],
                "summary": "문장 학습 히스토리",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "페이지 번호",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "페이지당 개수",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.PaginatedResponse"
                        }
                    }
                }
            }
        },
        "/api/sentences/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "문장 ID로 문장 상세 정보 조회 (단어 풀이, 문법, 예문 포함)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sentences"
                ],
                "summary": "문장 상세 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "문장 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sentences.SentenceDetailResponse"
                        }
                    }
                }
            }
        },
        "/api/stats/categories": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "오타쿠 카테고리별 학습 진행도 (애니, 게임, 성지순례, 이벤트)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "카테고리별 진행도 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/feedback.CategoryProgress"
                            }
                        }
                    }
                }
            }
        },
        "/api/stats/today": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "오늘의 학습 요약 통계 (사용 문장 수, 학습 시간, streak 등)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "오늘의 통계 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/feedback.StatsResponse"
                        }
                    }
                }
            }
        },
        "/api/stats/weekly": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "최근 7일간의 학습 통계",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "주간 통계 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/feedback.WeeklyStats"
                            }
                        }
                    }
                }
            }
        },
        "/api/user/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "현재 로그인한 유저의 정보 조회",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "내 정보 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                }
            }
        },
        "/api/user/onboarding": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "유저 온보딩 정보 저장 (레벨, 관심사, 목적)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "온보딩 정보 저장",
                "parameters": [
                    {
                        "description": "온보딩 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.OnboardingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UserOnboarding"
                        }
                    }
                }
            }
        },
        "/api/user/profile": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "유저 프로필 정보 수정",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "프로필 수정",
                "parameters": [
                    {
                        "description": "프로필 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                }
            }
        },
        "/api/user/settings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "유저 설정 정보 조회",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "설정 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UserSettings"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "유저 설정 정보 수정",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "설정 수정",
                "parameters": [
                    {
                        "description": "설정 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpdateSettingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UserSettings"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "auth.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "auth.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user": {}
            }
        },
        "chat.CreateSessionRequest": {
            "type": "object",
            "properties": {
                "daily_set_id": {
                    "type": "integer"
                }
            }
        },
        "chat.EndSessionRequest": {
            "type": "object",
            "properties": {
                "duration_seconds": {
                    "type": "integer"
                }
            }
        },
        "feedback.CategoryProgress": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "progress": {
                    "type": "number"
                }
            }
        },
        "feedback.StatsResponse": {
            "type": "object",
            "properties": {
                "average_score": {
                    "type": "number"
                },
                "current_streak": {
                    "type": "integer"
                },
                "total_learning_minutes": {
                    "type": "integer"
                },
                "total_sentences_used": {
                    "type": "integer"
                },
                "total_sessions": {
                    "type": "integer"
                }
            }
        },
        "feedback.WeeklyStats": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "minutes_spent": {
                    "type": "integer"
                },
                "sentences_learned": {
                    "type": "integer"
                },
                "session_count": {
                    "type": "integer"
                }
            }
        },
        "learning.UpdateProgressRequest": {
            "type": "object",
            "required": [
                "sentence_id"
            ],
            "properties": {
                "confirm": {
                    "type": "boolean"
                },
                "daily_set_id": {
                    "type": "integer"
                },
                "memorized": {
                    "type": "boolean"
                },
                "sentence_id": {
                    "type": "integer"
                },
                "speak": {
                    "type": "boolean"
                },
                "understand": {
                    "type": "boolean"
                }
            }
        },
        "model.ChatMessage": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "jp_text": {
                    "type": "string"
                },
                "kr_text": {
                    "type": "string"
                },
                "session_id": {
                    "type": "integer"
                },
                "speaker": {
                    "description": "\"ai\" or \"user\"",
                    "type": "string"
                },
                "used_sentence": {
                    "description": "Relations",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Sentence"
                        }
                    ]
                },
                "used_today_sentence_id": {
                    "description": "오늘 5문장 중 사용한 경우",
                    "type": "integer"
                }
            }
        },
        "model.ChatSession": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "daily_set_id": {
                    "type": "integer"
                },
                "duration_seconds": {
                    "type": "integer"
                },
                "ended_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ChatMessage"
                    }
                },
                "started_at": {
                    "type": "string"
                },
                "today_sentence_used_count": {
                    "description": "오늘 5문장 중 사용한 수",
                    "type": "integer"
                },
                "total_messages": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "model.Feedback": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "grammar_score": {
                    "description": "문법 점수",
                    "type": "number"
                },
                "highlights": {
                    "description": "하이라이트",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.FeedbackHighlight"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "naturalness_score": {
                    "description": "자연스러움 점수",
                    "type": "number"
                },
                "pronunciation_score": {
                    "description": "발음 점수",
                    "type": "number"
                },
                "session": {
                    "description": "Relations",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.ChatSession"
                        }
                    ]
                },
                "session_id": {
                    "type": "integer"
                },
                "summary": {
                    "description": "요약 문장",
                    "type": "string"
                },
                "total_score": {
                    "description": "총점",
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.FeedbackHighlight": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "jp": {
                    "type": "string"
                },
                "kr": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.LearningProgress": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "type": "string"
                },
                "confirm": {
                    "description": "확인하기 완료",
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "daily_set_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "memorized": {
                    "description": "암기 완료",
                    "type": "boolean"
                },
                "sentence": {
                    "$ref": "#/definitions/model.Sentence"
                },
                "sentence_id": {
                    "type": "integer"
                },
                "speak": {
                    "description": "말하기 완료",
                    "type": "boolean"
                },
                "understand": {
                    "description": "이해하기 완료",
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "model.Sentence": {
            "type": "object",
            "properties": {
                "audio_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "jp": {
                    "description": "일본어 문장",
                    "type": "string"
                },
                "kr": {
                    "description": "한국어 번역",
                    "type": "string"
                },
                "level": {
                    "description": "난이도 1~5",
                    "type": "integer"
                },
                "romaji": {
                    "description": "로마지",
                    "type": "string"
                },
                "tags": {
                    "description": "애니, 게임, 성지순례, 이벤트 등",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "onboarding": {
                    "$ref": "#/definitions/model.UserOnboarding"
                },
                "provider": {
                    "description": "local, google, kakao, etc.",
                    "type": "string"
                },
                "settings": {
                    "description": "Relations",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.UserSettings"
                        }
                    ]
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.UserOnboarding": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "interests": {
                    "description": "애니, 게임, 성지순례, 이벤트 등",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "level": {
                    "description": "0 ~ 5",
                    "type": "integer"
                },
                "purposes": {
                    "description": "학습 목적",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "model.UserSettings": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "daily_reminder_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "notification_enabled": {
                    "type": "boolean"
                },
                "preferred_voice_speed": {
                    "type": "number"
                },
                "show_romaji": {
                    "type": "boolean"
                },
                "show_translation": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "pkg.Meta": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "pkg.PaginatedResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "meta": {
                    "$ref": "#/definitions/pkg.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "pkg.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "sentences.DailySentencesResponse": {
            "type": "object",
            "properties": {
                "daily_set_id": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "sentences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sentences.SentenceResponse"
                    }
                }
            }
        },
        "sentences.SentenceDetailResponse": {
            "type": "object",
            "properties": {
                "examples": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "grammar": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sentence": {
                    "$ref": "#/definitions/sentences.SentenceResponse"
                },
                "words": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sentences.WordResponse"
                    }
                }
            }
        },
        "sentences.SentenceResponse": {
            "type": "object",
            "properties": {
                "audio_url": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "jp": {
                    "type": "string"
                },
                "kr": {
                    "type": "string"
                },
                "level": {
                    "type": "integer"
                },
                "romaji": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "sentences.WordResponse": {
            "type": "object",
            "properties": {
                "japanese": {
                    "type": "string"
                },
                "meaning": {
                    "type": "string"
                },
                "part_of": {
                    "type": "string"
                },
                "reading": {
                    "type": "string"
                }
            }
        },
        "service.TodayProgressResponse": {
            "type": "object",
            "properties": {
                "completed": {
                    "type": "integer"
                },
                "daily_set_id": {
                    "type": "integer"
                },
                "progress": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.LearningProgress"
                    }
                },
                "total_sentences": {
                    "type": "integer"
                }
            }
        },
        "user.OnboardingRequest": {
            "type": "object",
            "properties": {
                "interests": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "level": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 0
                },
                "purposes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "user.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "user.UpdateSettingsRequest": {
            "type": "object",
            "properties": {
                "daily_reminder_time": {
                    "type": "string"
                },
                "notification_enabled": {
                    "type": "boolean"
                },
                "preferred_voice_speed": {
                    "type": "number"
                },
                "show_romaji": {
                    "type": "boolean"
                },
                "show_translation": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
